# Generated by Django 2.1.7 on 2020-10-29 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201029_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 29, 12, 3, 12, 871199)),
        ),
    ]
